### ISSUE TITLE
register point property error

### ISSUE THREAD

**Issue by bothmer** [jakobkroeker/FiniteFieldExperiments.M2#73]
```
R = QQ[x,y,w,z]
mons3 = basis(3,R)
bbC = blackBoxParameterSpace(20,QQ);
cubicAt = point -> point*transpose mons3
bbC.registerPointProperty("cubicAt",cubicAt)
```

this does work if we replace the 4 th line by
```
cubicAt = (point) -> point*transpose mons3
```

i.e. with brackets around the parameter

**Comment by jakobkroeker** [comment]
bug was in (guess)AcceptedParameterNumber(). The function may not work correctly in all cases
but the example above should work now.
